<?php

use yii\db\Schema;
use yii\db\Migration;

class m260713_093617_allianceDataInsert extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->batchInsert('{{%alliance}}',
                           ["id", "status", "organization", "area_of_ceverage", "estimated_members", "alliance_leader_user_id", "alliance_leader_contact", "created_at", "alliance_leader_position"],
                            [
    [
        'id' => 1,
        'status' => 'active',
        'organization' => 'Helping Hands',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => 6,
        'alliance_leader_contact' => 1231231,
        'created_at' => '2026-07-08 01:25:35',
        'alliance_leader_position' => 'Chairman',
    ],
    [
        'id' => 2,
        'status' => 'active',
        'organization' => 'MFLAG (Marcos Forever Loyalist Alliance Group)',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => 5,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:25:35',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 3,
        'status' => 'active',
        'organization' => 'One Cainta task force',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => 6,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:44:29',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 4,
        'status' => 'active',
        'organization' => 'Maagap Squadron Eagles Club, President',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => 0,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:44:29',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 5,
        'status' => 'active',
        'organization' => 'ACSAF-National',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => 0,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:44:29',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 6,
        'status' => 'active',
        'organization' => 'Balikatan Peoples Alliance',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => 0,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:44:29',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 7,
        'status' => 'active',
        'organization' => '1LGBT FILIPINAS INC.',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => 5,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:44:29',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 8,
        'status' => 'active',
        'organization' => 'KBM Coalition',
        'area_of_ceverage' => 'Nationwide',
        'estimated_members' => null,
        'alliance_leader_user_id' => 0,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:44:29',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 9,
        'status' => 'active',
        'organization' => 'STL (Selected Team Leaders)',
        'area_of_ceverage' => 'International',
        'estimated_members' => null,
        'alliance_leader_user_id' => 0,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:44:29',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 10,
        'status' => 'active',
        'organization' => 'FILSCAP',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => 0,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:44:29',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 11,
        'status' => 'active',
        'organization' => 'KKMI (Kapatiran, Kasipagan, May Malasakit Inc.)',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:45:15',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 12,
        'status' => 'active',
        'organization' => 'Bagong Bayang Maharlika (Wisdom Church)',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 13,
        'status' => 'active',
        'organization' => 'Samahang Ilocano-Taguig',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 14,
        'status' => 'active',
        'organization' => 'Imelda Dy Group',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 15,
        'status' => 'active',
        'organization' => 'Diamond Action Group, Inc.',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 16,
        'status' => 'active',
        'organization' => 'Bigkis ng Bagong Pilipinas',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 17,
        'status' => 'active',
        'organization' => 'Solidarity Philippines Group, Inc.',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 18,
        'status' => 'active',
        'organization' => 'Alliance in Missions for the Least Reached People Group, Inc',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 19,
        'status' => 'active',
        'organization' => 'LGBT Pilipinas',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 20,
        'status' => 'active',
        'organization' => 'Kaakbay sa Kabuhayan ng Payatas Ass., Inc.',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:49:33',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 21,
        'status' => 'active',
        'organization' => 'AFMI(Alliance of Filipino Masses International)',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 22,
        'status' => 'active',
        'organization' => 'Solo Parent',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 23,
        'status' => 'active',
        'organization' => 'TSBS (Taguig Solid BBM Supporters)',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 24,
        'status' => 'active',
        'organization' => 'KAISA ng Bagong Pilipinas',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 25,
        'status' => 'active',
        'organization' => 'Barkadahan ng Sampaloc',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 26,
        'status' => 'active',
        'organization' => 'Filipino Internation League',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 27,
        'status' => 'active',
        'organization' => 'Agila ng Bagong Pilipinas',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 28,
        'status' => 'active',
        'organization' => 'BBMD',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 29,
        'status' => 'active',
        'organization' => 'ISARO (Informal Settler and Renter Organization)',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 30,
        'status' => 'active',
        'organization' => 'SAMAKA',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:53:06',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 31,
        'status' => 'active',
        'organization' => 'Hills Summit Farmers Association Inc.',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 32,
        'status' => 'active',
        'organization' => 'Pamplona Uno Merging Alliance FloaT',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 33,
        'status' => 'active',
        'organization' => 'Abesalden Group ',
        'area_of_ceverage' => 'Nationwide',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 34,
        'status' => 'active',
        'organization' => 'OFW',
        'area_of_ceverage' => 'International',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 35,
        'status' => 'active',
        'organization' => 'BKSP (Bagong Kilusan Sigla ng Pilipino)',
        'area_of_ceverage' => 'Nationwide',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 36,
        'status' => 'active',
        'organization' => 'Sang-At Agri Farm and Venture of Earth Planters Association Inc, President',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 37,
        'status' => 'active',
        'organization' => 'OMI-Vlogger',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 38,
        'status' => 'active',
        'organization' => 'Tiger Task Force',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 39,
        'status' => 'active',
        'organization' => 'KNNB (Kilusan ng Nagkakaisang Bulakeño)',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 40,
        'status' => 'active',
        'organization' => 'USWAG (Unified Servants for Welfare and Active Governance)',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:56:38',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 41,
        'status' => 'active',
        'organization' => 'KBSL Bayang Banal Masagana Inc.',
        'area_of_ceverage' => 'Nationwide',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 42,
        'status' => 'active',
        'organization' => 'Sunrise Alliance',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 43,
        'status' => 'active',
        'organization' => 'People\'s Alliance Group Organization Inc.',
        'area_of_ceverage' => 'Nationwide',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 44,
        'status' => 'active',
        'organization' => 'OMI-Al Ace Caloocan',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 45,
        'status' => 'active',
        'organization' => 'OMI-Lemery Batangas',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 46,
        'status' => 'active',
        'organization' => 'OMI-Baseco',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 47,
        'status' => 'active',
        'organization' => 'OMI-Cainta',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 48,
        'status' => 'active',
        'organization' => 'OMI-QC Fairview',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 49,
        'status' => 'active',
        'organization' => 'OMI-QC Pag Asa',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 50,
        'status' => 'active',
        'organization' => 'OMI-QC Payatas Lupang Pangako',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 01:59:25',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 51,
        'status' => 'active',
        'organization' => 'OMI-Tagaytay',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 02:00:41',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 52,
        'status' => 'active',
        'organization' => 'OMI_Valenzuela',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 02:00:41',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 53,
        'status' => 'active',
        'organization' => 'OMI-QC District 2',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 02:00:41',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 54,
        'status' => 'active',
        'organization' => 'OMI-QC Central',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 02:00:41',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 55,
        'status' => 'active',
        'organization' => 'OMI-Dasmarinas',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 02:00:41',
        'alliance_leader_position' => null,
    ],
    [
        'id' => 56,
        'status' => 'active',
        'organization' => 'OMI-QC Commonwealth',
        'area_of_ceverage' => 'Luzon',
        'estimated_members' => null,
        'alliance_leader_user_id' => null,
        'alliance_leader_contact' => null,
        'created_at' => '2026-07-08 02:00:41',
        'alliance_leader_position' => null,
    ],
]
        );
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%alliance}} CASCADE');
    }
}
